/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
var View=Laya.View;
var Dialog=Laya.Dialog;
var Scene=Laya.Scene;
var REG = Laya.ClassUtils.regClass;
export class GameViewUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("test/GameView");
	}
}
REG("ui.test.GameViewUI",GameViewUI);
export class TestSceneUI extends Scene {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("test/TestScene");
	}
}
REG("ui.test.TestSceneUI",TestSceneUI);
export class WinViewUI extends View {
	constructor(){ 
		super();
	}
	createChildren() {
		super.createChildren();
		this.loadScene("test/WinView");
	}
}
REG("ui.test.WinViewUI",WinViewUI);