/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameView from "./script/GameView"
import TestSceneView from "./script/TestSceneView"
import WinView from "./script/WinView"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("script/GameView.js",GameView);
		reg("script/TestSceneView.js",TestSceneView);
		reg("script/WinView.js",WinView);
    }
}
GameConfig.width = 750;
GameConfig.height = 1334;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "middle";
GameConfig.alignH = "center";
GameConfig.startScene = "test/TestScene.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = true;
GameConfig.exportSceneToJson = true;

GameConfig.init();
